apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: eval
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: lgeorges1234/k8s-dst-eval-fastapi:latest
        ports:
        - containerPort: 8000
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3307"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE  
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: MYSQL_DATABASE