apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: eval
  labels:
    app: fastapi
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
    protocol: TCP
    