apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-data-folder-pv
  labels:
    app: mysql
    type: local
    storage: local
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: eval
     name: mysql-data-mysql-0
  hostPath:
    path: "/mnt/data"