apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
  namespace: eval
type: Opaque
data:
  password: RGF0YXNjaWVudGVzdDIwMjNAISE=
  # The password is base64 encoded. You can decode it using the following command:
  # echo "RGF0YXNjaWVudGVzdDIwMjNAISE=" | base64 --decode
  # This will output: datascientest2023@!

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-user
  namespace: eval
type: Opaque
data:
  MARIADB_USER: ZXZhbHVzZXI=  # Base64 encoded evaluser
  MARIADB_PASSWORD: ZXZhbG15c3FsQC4u  # Base64 encoded evalmysql@..
  MARIADB_DATABASE: ZGF0YXNj  # Base64 encoded datasc